"""Bristol Airport (BRS) destinations — May 2026."""

DESTINATIONS = {
    "BRS": {
        "name": "Bristol",
        "routes": {
            "ABZ": "Aberdeen",
            "ACE": "Lanzarote",
            "AGA": "Agadir",
            "AGP": "Malaga",
            "ALC": "Alicante",
            "AMS": "Amsterdam",
            "ATH": "Athens",
            "AYT": "Antalya",
            "BCN": "Barcelona",
            "BER": "Berlin",
            "BFS": "Belfast Intl",
            "BGO": "Bergen",
            "BHD": "Belfast City",
            "BJV": "Bodrum",
            "BOD": "Bordeaux",
            "BOJ": "Bourgas",
            "BRI": "Bari",
            "BSL": "Basel",
            "BUD": "Budapest",
            "BZG": "Bydgoszcz",
            "BZR": "Beziers",
            "CDG": "Paris CDG",
            "CFU": "Corfu",
            "CMF": "Chambery",
            "CPH": "Copenhagen",
            "CTA": "Catania",
            "DBV": "Dubrovnik",
            "DLM": "Dalaman",
            "DUB": "Dublin",
            "EDI": "Edinburgh",
            "EFL": "Kefalonia",
            "EGC": "Bergerac",
            "ENF": "Enontekio",
            "FAO": "Faro",
            "FCO": "Rome",
            "FNC": "Funchal",
            "FUE": "Fuerteventura",
            "GCI": "Guernsey",
            "GDN": "Gdansk",
            "GIB": "Gibraltar",
            "GLA": "Glasgow",
            "GNB": "Grenoble",
            "GRO": "Girona",
            "GVA": "Geneva",
            "HER": "Heraklion",
            "IBZ": "Ibiza",
            "INN": "Innsbruck",
            "INV": "Inverness",
            "IOM": "Isle of Man",
            "IVL": "Ivalo",
            "JER": "Jersey",
            "JSI": "Skiathos",
            "JTR": "Santorini",
            "KEF": "Reykjavik",
            "KGS": "Kos",
            "KLX": "Kalamata",
            "KRK": "Krakow",
            "KTT": "Kittila",
            "KUN": "Kaunas",
            "LCA": "Larnaca",
            "LEI": "Almeria",
            "LIG": "Limoges",
            "LIS": "Lisbon",
            "LPA": "Gran Canaria",
            "LRH": "La Rochelle",
            "LYS": "Lyon",
            "MAD": "Madrid",
            "MAH": "Menorca",
            "MLA": "Malta",
            "MRS": "Marseille",
            "MUC": "Munich",
            "MXP": "Milan",
            "NAP": "Naples",
            "NBE": "Enfidha",
            "NCE": "Nice",
            "NCL": "Newcastle",
            "NOC": "Knock",
            "OLB": "Olbia",
            "OPO": "Porto",
            "ORK": "Cork",
            "OTP": "Bucharest",
            "PFO": "Paphos",
            "PMI": "Palma",
            "PMO": "Palermo",
            "POZ": "Poznan",
            "PRG": "Prague",
            "PSA": "Pisa",
            "PUY": "Pula",
            "PVK": "Preveza",
            "RAK": "Marrakech",
            "REU": "Reus",
            "RHO": "Rhodes",
            "RMU": "Murcia",
            "RVN": "Rovaniemi",
            "RZE": "Rzeszow",
            "SAW": "Istanbul",
            "SKG": "Thessaloniki",
            "SMI": "Symi",
            "SOF": "Sofia",
            "SPU": "Split",
            "SVQ": "Seville",
            "SZG": "Salzburg",
            "TFS": "Tenerife",
            "TIV": "Tivat",
            "TLS": "Toulouse",
            "TOS": "Tromso",
            "TRN": "Turin",
            "VCE": "Venice",
            "VIE": "Vienna",
            "VLC": "Valencia",
            "VRN": "Verona",
            "WRO": "Wroclaw",
            "ZRH": "Zurich",
            "ZTH": "Zakynthos",
        },
    },
}


def get_destinations(airport: str) -> dict:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("routes", {})


def get_airport_name(airport: str) -> str:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("name", airport)
